# Generated by Django 4.0.3 on 2022-03-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='iban',
            field=models.ManyToManyField(to='main.iban'),
        ),
    ]
