# Generated by Django 4.0.3 on 2022-03-28 21:08

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_iban_iban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='iban',
        ),
        migrations.AddField(
            model_name='profile',
            name='iban',
            field=models.IntegerField(null=True, verbose_name=localflavor.generic.models.IBANField),
        ),
    ]
