# Generated by Django 4.0.3 on 2022-03-28 21:15

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_iban_profile_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iban',
            field=models.TextField(null=True, verbose_name=localflavor.generic.models.IBANField),
        ),
    ]
